#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Harri.SchoolDemoAPI/ && \
    dotnet build src/Harri.SchoolDemoAPI/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Harri.SchoolDemoAPI/Harri.SchoolDemoAPI.csproj --launch-profile web"
