
INSERT INTO [SchoolDemo].School (schoolName, state, enrollment) VALUES
('Sunshine Valley Academy', 'QLD', 3498),
('Northern Ridge High School', 'NSW', 2587),
('Hobart Collegiate Institute', 'TAS', 1034),
( 'Melbourne Future School', 'VIC', 4500),
( 'West Coast Education Centre', 'WA', 3975),
( 'Southern Cross Grammar', 'SA', 2146),
( 'Capital City Academy', 'ACT', 1289),
( 'Outback Learning Hub', 'NT', 1720),
( 'Riverdale Comprehensive School', 'QLD', 3458),
( 'Eastern Heights College', 'NSW', 4671),
( 'Tasman National School', 'TAS', 1893),
( 'Victorian Tech School', 'VIC', 3039),
( 'Perth Modern Institute', 'WA', 3555),
( 'Adelaide Leadership Academy', 'SA', 2207),
( 'Canberra Scholars College', 'ACT', 1422),
( 'Darwin International School', 'NT', 1834),
( 'Coastal View High School', 'QLD', 3127),
( 'Sydney Progressive School', 'NSW', 4298),
( 'Tasmania Science College', 'TAS', 2077),
( 'Victoria Arts School', 'VIC', 4001),
( 'Western Horizon University', 'WA', 4903),
( 'South Australia Institute of Technology', 'SA', 2890),
( 'Australian Capital Educational Centre', 'ACT', 1759),
( 'Northern Territory Polytechnic', 'NT', 2615);