parameters:
  state: ''
  description: ''
  context: 'HarrisonSlater.Harri.SchoolDemoApi'

steps:
- script: 'echo ''{"state":"${{ parameters.state }}","description":"${{ parameters.description }}","context":"${{ parameters.context }}"}'''
- script: |
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $(GitHubChecksPAT)" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/HarrisonSlater/Harri.SchoolDemoAPI/statuses/$(CommitIdForGitHub) \
      -d \
      '{"state":"${{ parameters.state }}","description":"${{ parameters.description }}","context":"${{ parameters.context }}"}'