/*
 * Swagger School ADMIN - OpenAPI 3.0
 *
 * Demo API about students, schools, and students applications to schools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Harri.SchoolDemoAPI.Converters;

namespace Harri.SchoolDemoAPI.Models
{ 
        /// <summary>
        /// List of valid decisions a school can make on an application
        /// </summary>
        /// <value>List of valid decisions a school can make on an application</value>
        [TypeConverter(typeof(CustomEnumConverter<Decision>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum Decision
        {
            
            /// <summary>
            /// Enum YEnum for Y
            /// </summary>
            [EnumMember(Value = "Y")]
            YEnum = 1,
            
            /// <summary>
            /// Enum NEnum for N
            /// </summary>
            [EnumMember(Value = "N")]
            NEnum = 2
        }
}
