/*
 * Swagger School ADMIN - OpenAPI 3.0
 *
 * Demo API about students, schools, and students applications to schools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Harri.SchoolDemoAPI.Converters;

namespace Harri.SchoolDemoAPI.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class NumberQuery 
    {
        /// <summary>
        /// less than
        /// </summary>
        /// <value>less than</value>
        /// <example>3.5</example>
        [DataMember(Name="lt", EmitDefaultValue=true)]
        public decimal? Lt { get; set; }

        /// <summary>
        /// greater than
        /// </summary>
        /// <value>greater than</value>
        /// <example>2.2</example>
        [DataMember(Name="gt", EmitDefaultValue=true)]
        public decimal? Gt { get; set; }

        /// <summary>
        /// equal to
        /// </summary>
        /// <value>equal to</value>
        /// <example>4</example>
        [DataMember(Name="eq", EmitDefaultValue=true)]
        public decimal? Eq { get; set; }

        /// <summary>
        /// is null
        /// </summary>
        /// <value>is null</value>
        /// <example>true</example>
        [DataMember(Name="isnull", EmitDefaultValue=true)]
        public bool? Isnull { get; set; }

    }
}
