/*
 * Swagger School ADMIN - OpenAPI 3.0
 *
 * Demo API about students, schools, and students applications to schools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Harri.SchoolDemoAPI.Converters;

namespace Harri.SchoolDemoAPI.Models
{ 
        /// <summary>
        /// List of valid states
        /// </summary>
        /// <value>List of valid states</value>
        [TypeConverter(typeof(CustomEnumConverter<State>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum State
        {
            
            /// <summary>
            /// Enum QLDEnum for QLD
            /// </summary>
            [EnumMember(Value = "QLD")]
            QLDEnum = 1,
            
            /// <summary>
            /// Enum NSWEnum for NSW
            /// </summary>
            [EnumMember(Value = "NSW")]
            NSWEnum = 2,
            
            /// <summary>
            /// Enum VICEnum for VIC
            /// </summary>
            [EnumMember(Value = "VIC")]
            VICEnum = 3,
            
            /// <summary>
            /// Enum ACTEnum for ACT
            /// </summary>
            [EnumMember(Value = "ACT")]
            ACTEnum = 4,
            
            /// <summary>
            /// Enum TASEnum for TAS
            /// </summary>
            [EnumMember(Value = "TAS")]
            TASEnum = 5,
            
            /// <summary>
            /// Enum WAEnum for WA
            /// </summary>
            [EnumMember(Value = "WA")]
            WAEnum = 6,
            
            /// <summary>
            /// Enum NTEnum for NT
            /// </summary>
            [EnumMember(Value = "NT")]
            NTEnum = 7,
            
            /// <summary>
            /// Enum SAEnum for SA
            /// </summary>
            [EnumMember(Value = "SA")]
            SAEnum = 8
        }
}
